# Guide: https://coderefinery.github.io/documentation/gh_workflow/

name: Documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install distclassipy
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .
      - name: Install sphinx dependencies
        run: |
          if [ -f docs/requirements.txt ]; then python3 -m pip install -r docs/requirements.txt; fi
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc
      - name: Sphinx build
        run: |
          sphinx-build -T -E -b html -d docs/build/doctrees ./docs docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true