# Guide: https://coderefinery.github.io/documentation/gh_workflow/

name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          if [ -f docs/requirements.txt ]; then python3 -m pip install -r docs/requirements.txt; fi
          python3 -m pip install .
      - name: Sphinx build
        run: |
          sphinx-build -T -E -b html -d docs/build/doctrees ./docs docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true