name: Linter

on: [push, pull_request]    

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./distclassipy"
        jupyter: true
        version: "~= 24.0"
    - name: Run flake8
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        pip install flake8
        flake8 --extend-ignore=E203,E701 --max-line-length 88 tests/ distclassipy setup.py --show-source --statistics
    - name: Run pydocstyle
      run: |
        pip install pydocstyle
        pydocstyle distclassipy --convention=numpy
