# Guide: https://shrra.github.io/python-intermediate-development/23-continuous-integration-automated-testing/index.html

name: CI

# We can specify which Github events will trigger a CI build
on: push

# now define a single job 'build' (but could define more)
jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    # a job is a seq of steps
    steps:

    # Next we need to checkout out repository, and set up Python
    # A 'name' is just an optional label shown in the log - helpful to clarify progress - and can be anything
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .
        python3 -m pip install pytest pytest-cov

    - name: Test classifier model with PyTest
      run: |
        python3 -m pytest tests/test_classifier.py --cov=distclassipy.classifier --cov-report=xml

    - name: Test distance functions with PyTest
      run: |
        python3 -m pytest tests/test_distances.py --cov=distclassipy.distances --cov-report=xml